# For more info on HTTP files go to https://aka.ms/vs/httpfile
@schema=https
@hostname=localhost
@port=7183

GET {{schema}}://{{hostname}}:{{port}}/api/v2/cities/6/mustVisit
###
POST {{schema}}://{{hostname}}:{{port}}/api/v2/cities/6/mustVisit
Accept: application/json
Content-Type: application/json

{
  "name":"Testing",
  "description":"Testing description"
}
###
POST {{schema}}://{{hostname}}:{{port}}/api/authentication/authenticate
Content-Type: application/json

{
    "username":"VishwasGandhi",
    "password":"This is my password"
}

###
GET {{schema}}://{{hostname}}:{{port}}/api/v1/cities
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IlZpc2h3YXMiLCJmYW1pbHlfbmFtZSI6IkdhbmRoaSIsImNpdHkiOiJNaWFtaSIsIm5iZiI6MTcxMjc1MzI2OCwiZXhwIjoxNzEyNzU2ODY4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MTY5IiwiYXVkIjoiY2l0eWluZm9hcGkifQ.2E8gJnvz6LENy29C_73xSzEO3jiAlzhqByJARmLFMzk
